retrieveUnpackaged/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Store__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Store</label>
        <referenceTo>Store__c</referenceTo>
        <relationshipLabel>Brands</relationshipLabel>
        <relationshipName>Brands</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brands Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Brand__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brand</label>
        <referenceTo>Brand__c</referenceTo>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Products</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Questionn__c.object
<CustomObject>
    <fields>
        <fullName>Products__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Products</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Questions</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Store__c.object
<CustomObject>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Surveyy__c.object
<CustomObject>
    <fields>
        <fullName>Answer_1__c</fullName>
        <label>Answer 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Question_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question 1</label>
        <referenceTo>Questionn__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Surveys</label>
    <nameField>
        <displayFormat>SV{000}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/getRecords.cls
public class getRecords {
    @AuraEnabled 
    public static List<Store__c> recordss()
    {
        return [select id,Name from Store__c];
    }
    
    @AuraEnabled
    public static List<Brand__c> bRecords(String Store_id)
    {
        return [select id,Name from Brand__c where Store__c=:Store_id];
    }
    
    @AuraEnabled
    public static List<Product__c> pRecords(String Product_id)
    {
        return [select id,Name from Product__c where Brand__c=:Product_id];
    }
    
    @AuraEnabled
    public static List<Questionn__c> qRecords(String Question_id)
    {
        return [select id,Name from Questionn__c where Products__c=:Question_id];
    }
    
    @AuraEnabled
    public static void InsertSurvey(String Question1,String Answer1)
    {
        Surveyy__c sv=new Surveyy__c();
        sv.Question_1__c=Question1;
        sv.Answer_1__c=Answer1;
        insert sv;
        
    }

}