retrieveUnpackaged/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <description>address of the employee</description>
        <label>Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <description>Zip Code of a place</description>
        <label>Zip Code</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Zip_Code__c.object
<CustomObject>
    <fields>
        <fullName>zip_code__c</fullName>
        <label>zip code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/newCandidate.cls
public class newCandidate {

    public String getAccount() {
        return null;
    }


    public PageReference save() {
        return null;
    }

    public Candidate__c noob{get;set;}

    
    
    
    public newCandidate()
    {
    noob=new Candidate__c();
    }
  
    public void createNew() {
                
    insert noob;
    
        
    }



  
   
   

    public List<Candidate__c> getRecords() 
    {
        List<Candidate__c> ls=[select Name,Address__c,Zip_Code__c from Candidate__c];
        return ls;
    }

}