retrieveUnpackaged/objects/Junk__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Junks</relationshipLabel>
        <relationshipName>Junks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ManyName__c</fullName>
        <label>Many</label>
        <referenceTo>Many__c</referenceTo>
        <relationshipLabel>Junks</relationshipLabel>
        <relationshipName>Junks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Junk</label>
    <nameField>
        <displayFormat>A-{00}</displayFormat>
        <label>Junk N0</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Junks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Many__c.object
<CustomObject>
    <label>Many</label>
    <nameField>
        <label>Many Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>mannyyy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/records.cls
public class records {

    public PageReference enter() {
    selectedJunk.clear();
    for(accountwrapper1 accwrapper : junkList){
    if(accwrapper.selected==true)
    {
    Junk__c selecteddJunk=new Junk__c();
    selecteddJunk.AccountName__c=i;
    selecteddJunk.ManyName__c =accwrapper.jnk.ManyName__c ;
    insert selecteddJunk;
       }
       
       }
        return null; 
    }



             
             
   public records(ApexPages.StandardSetController controller) 
   {
   i=ApexPages.currentPage().getParameters().get('Accid'); 
   xyzz=[select ManyName__c from Junk__c];
   selectedJunk=[select ManyName__c from Junk__c where AccountName__c=:i];
   selectMany=[select Name from Many__c];
    }

   

 String i;
         public Junk__c jnk{get; set;}
 public accountwrapper1 abcc=new accountwrapper1();    
 public List<Junk__c> selectedJunk=new List<Junk__c>();
 List<accountwrapper1> junkList= new List<accountwrapper1>();
 public List<Junk__c>xyzz=new List<Junk__c>();
 public List<Junk__c> selectedJnk=new List<Junk__c>();
 public List<Many__c> selectMany=new List<Many__c>();


  

  public List<accountwrapper1> getXyz(){
  for(Junk__c j:[select  ManyName__c from Junk__c])
  junkList.add(new accountwrapper1(j));

    return  junkList;
    }
   
    public records(ApexPages.StandardController controller) {

    } 
         
     public class accountwrapper1
    {
        public Junk__c jnk{get; set;}
        public Boolean selected {get; set;}
        public accountwrapper1(Junk__c a)
        {
            jnk = a;
            selected = false;
        }
        public accountwrapper1()
        {
        }
        
}



}