retrieveUnpackaged/objects/Notification__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Created_Date__c</fullName>
        <label>Created Date</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event_Type__c</fullName>
        <label>Event Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Id__c</fullName>
        <label>Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Name__c</fullName>
        <label>Record Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Notification</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/accnt.cls
public class accnt { 


    public  list<Account> getAcca() {
     acc=[select id,name from account];
        return acc;
    }

    public list<Account> acc {get; set;}    
    public list<Notification__c> not1 {get;set;}    
    public accnt(){
       batchNotifications BatchNot=new batchNotifications();
           Database.executeBatch(BatchNot);
    }
     public list<Notification__c> getNotifications() {
        not1 = [select id,Name,Channel__c,Created_Date__c,Event_Type__c,Id__c,Record_Name__c from Notification__c];
        return not1;
    }
}